name:                climb
version:             0.5.1
github:              "ejconlon/climb"
license:             BSD3
author:              "Eric Conlon"
maintainer:          "ejconlon@gmail.com"
copyright:           "(c) 2019 Eric Conlon"
category:            User Interfaces
synopsis:            Building blocks for a GHCi-like REPL with colon-commands

extra-source-files:
- README.md

description: Please see the README on GitHub at <https://github.com/ejconlon/climb#readme>

dependencies:
- base >=4.12 && <5
- bytestring >=0.10 && <1
- containers >=0.6 && <1
- exceptions >=0.10 && <1
- linenoise >=0.4.2 && <1
- mtl >=2.2 && <3
- text >=1.2 && <3
- unliftio-core >=0.1 && <1

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints
- -fno-warn-unused-top-binds

default-extensions:
- DerivingStrategies
- GeneralizedNewtypeDeriving

library:
  source-dirs: src

executables:
  climb-demo:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - climb
